version: '3.7'
services:
  projet:
  build:
   context : ./mvc/
   dockerfile : dockerfile
  container_name: project
  volumes:
   - ./:/var/www
  tty: true
  expose :
   - "5000"
  restart : always
  networks:
   - app-network

  depends_on:

   - nginx
 nginx:

  image: nginx:alpine

  volumes:

   - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  ports:

   - "4001:80"
  networks:
   - app-network
  restart : always
#Docker Networks
#connexion entre les conatainers
networks:

 app-network:

  driver: bridge



